[project]
name = "no-tang-doc-agent"
version = "0.1.0"
description = "no-tang-doc-agent"
readme = "README.md"
requires-python = ">=3.13.5, <3.14"
dependencies = [
    "fast-agent-mcp>=0.3.17",
    "mcp[cli]>=1.19.0",
]
